name: Continuous integration workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up Python
        run: uv python install 3.11

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Install ruff explicitly
        run: uv pip install ruff

      - name: Verify ruff installation
        run: uv run ruff --version

      - name: Check format
        run: uv run ruff check

      - name: Run tests
        run: uv run pytest tests